# Change these first
owner: betagouv # Your GitHub username
repo: api-particulier-status # Your GitHub repository name

# Add your sites here
sites:
  - name: API Particulier
    url: https://particulier.api.gouv.fr/api/ping

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.particulier.api.gouv.fr
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: API Particulier
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/betagouv/api-particulier

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
